p "a fasten your seatbelts it's going to be a bumpy night".scan(/\w/).values_at(9,35,26)
p "a on second thought lets not go to camelot it is a silly place".scan(/\w/).values_at(3,38,28)
p "a help me obi wan kenobi you're my only hope".scan(/\w/).values_at(6,13,24)
p "a tell em to go out there with all they got and win just one for the gipper".scan(/\w/).values_at(23,45,5)
p "a i'll get you my pretty and your little dog too".scan(/\w/).values_at(25,6,18)
p "a first rule of fight club is you do not talk about fight club".scan(/\w/).values_at(2,37,17)
p "a you've got to ask yourself one question do i feel lucky well do you punk".scan(/\w/).values_at(19,45,8)
p "a louis i think this is the beginning of a beautiful friendship".scan(/\w/).values_at(25,45,2)
p "a face it girls im older and i have more insurance".scan(/\w/).values_at(33,9,18)
